import { ENV } from "./env";

export const developmentOther = {
    APPLICATION_ID: ENV.APPLICATION_ID,
    APPLICATION_KEY: ENV.APPLICATION_KEY,
    REDIS_HOST: ENV.REDIS_HOST,
    REDIS_PORT: ENV.REDIS_PORT,
    DISTRIBUTOR_WALLET_PRIVATE_KEY: ENV.DISTRIBUTOR_WALLET_PRIVATE_KEY,
};

export const productionOther = {
    APPLICATION_ID: ENV.APPLICATION_ID,
    APPLICATION_KEY: ENV.APPLICATION_KEY,
    REDIS_HOST: ENV.REDIS_HOST,
    REDIS_PORT: ENV.REDIS_PORT,
    DISTRIBUTOR_WALLET_PRIVATE_KEY: ENV.DISTRIBUTOR_WALLET_PRIVATE_KEY,
};
